[package]
name = "ltk_mesh"
version = "0.5.3"
edition = "2021"
description = "Mesh parsing and structures for League Toolkit"
license = "Apache-2.0"
readme = "../../README.md"

[lints]
workspace = true

[features]
tangent-baking = ["dep:bevy_mikktspace"]

[dependencies]
byteorder = { workspace = true }
bitflags = { workspace = true }
num_enum = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
bevy_mikktspace = { workspace = true, optional = true }

glam = { workspace = true }
half = { workspace = true }

ltk_io_ext = { version = "0.4.7", path = "../ltk_io_ext" }
ltk_primitives = { version = "0.3.6", path = "../ltk_primitives" }
