[package]
name = "league-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.60"
glam = { version = "0.27.0", features = ["glam-assert"] }
byteorder = "1.5.0"
serde = { version = "1.0.204", features = ["derive"], optional = true }
