[workspace]
pr_draft = true                                   # draft the release PR
changelog_path = "./CHANGELOG.md"
git_tag_name = "{{ package }}-v{{ version }}"     # tag name
git_release_name = "{{ package }} v{{ version }}" # release name
git_release_body = "{{ changelog }}"              # release body
pr_branch_prefix = "release-plz-"                 # PR branch prefix
pr_labels = ["release"]                           # add the `release` label to the release Pull Request
release_commits = "^(feat|fix|perf)"              # only feat/fix/perf commits trigger a release
