[package]
name = "span"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
serde = ["dep:serde"]
derive = ["dep:span_derive"]

[dependencies]
span_derive = {version = "0.1.0", path = "../span_derive/", optional = true}
serde = {workspace = true, optional = true}

[lints]
workspace = true
