[package]
name = "io-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.60"
league-primitives = { path = "../league-primitives" }
byteorder = "1.5.0"
glam = { version = "0.27.0", features = ["glam-assert"] }
